AGGREGATE_ENDPOINT: https://int-api-atlas-core-mt01.atlasconsolidated.com

customer_id: e157a745-c9f9-5724-b726-8eaed308fb08
customer_profile_id: b287e434-52fe-5da1-a35d-df09b12bc08f
customer_id_2: c56734e3-a682-544c-b4e9-4e0877dd1ec0
customer_profile_id_2: e760a875-f3c0-5cb0-99d8-39ccc2754728
pk_customer_profile_id: 9b94dcde-39a7-5733-ad82-c87c6fac8fe4
